### ISSUE TITLE
[Question] Control playback

### ISSUE THREAD

**Issue by olikami** [Werter12/material-ui-audio-player#138]
Is there a way to control playback programmatically? For example, I would like to start the player after a user presses a different button somewhere else.

**Comment by Werter12** [comment]
At the moment this is impossible, cause the `player` ref assigned to the `audio` tag inside the component and there is no way to pass the ref from the above. We can accomplish this by wrapping the component in the `forwardRef` in order to pass ref.  Also, the default ref should be overwritten by the passed ref. So there are several difficulties related to typing here. I am going to work on this in the future, cause requests on managing `audio` programmatically becoming quite popular.

**Comment by Werter12** [comment]
@olikami I've managed to add `getPlayer` function for the component. So, I could manipulate `player` from external. But, what has left to do is to make the component responsive to player state changes. For example now when I press the external play/pause button the slider of progress is moving but the component play button doesn't respond to that state change from an external source. PR: https://github.com/Werter12/material-ui-audio-player/pull/154

**Comment by Werter12** [comment]
@olikami Hi! I've just released a new version https://github.com/Werter12/material-ui-audio-player/compare/v1.6.7...v1.7.0 of the package. Direct access to the HTML audio player has been added. Now you can change playback programmatically. Check out the "Controlled AudioPlayer" section in the storybook demo and documentation.
