### ISSUE TITLE
Setting a data uri as the src value results in the duration being displayed as NaN:NaN

### ISSUE THREAD

**Issue by abeluck** [Werter12/material-ui-audio-player#162]
When you use a base64 encoded audio file in a data uri (such as `data:audio/webm;base64,AAAA...`) and pass it to this (wonderful) component, the duration is displayed as NaN:NaN.

After playing the audio once and clicking the reset arrow, then the duration is correctly displayed.

related to: https://github.com/Werter12/material-ui-audio-player/issues/82

**Comment by Werter12** [comment]
@abeluck I've tried several base64 encoded audios and couldn't saw the issue. If you send me your encoded file, I could debug it more precisely. My email: samofan77@gmail.com

**Comment by Werter12** [comment]
@abeluck Thanks for sending me an example file! It helped me to identify and fix the issue. Turned out that it is a [browser bug](https://bugs.chromium.org/p/chromium/issues/detail?id=642012) related to the perception of the audio tag the `webm` format. Instead of the number duration of the audio was Infinite. Then after replay duration became right. So, I have added a little trick to make the duration work properly. Release `v1.5.2`.
