### ISSUE TITLE
how to use custom icons

### ISSUE THREAD

**Issue by callmejm** [Werter12/material-ui-audio-player#371]
I wish pass my inline svg component to overwrite the existing icon

	import PlayIcon from "../../images/svg/play.inline.svg";
	import PauseIcon from "../../images/svg/pause.inline.svg"
	import ReplayIcon from "../../images/svg/replay.inline.svg"
	import SoundOnIcon from "../../images/svg/soundon.inline.svg"
	import SoundOffIcon from "../../images/svg/soundoff.inline.svg"
	const icons = {
	  PlayIcon: PlayIcon,
	  ReplayIcon: ReplayIcon,
	  PauseIcon: PauseIcon,
	  VolumeUpIcon: SoundOnIcon,
	  VolumeOffIcon: SoundOffIcon
	}

**Comment by Werter12** [comment]
At the moment we are using only `material-ui/icons`. In order to use custom .svg icons, the project should have a specific webpack loader according to https://material-ui.com/ru/components/icons/ . You can open PR with custom .svg support and we will consider if that complexity that custom icons could introduce - worth it. My personal opinion that `material-icons` should be enough for this project. Cause it depends fully on material UI infrastructure.
