### ISSUE TITLE
Clicking current play time should toggle remaining play time

### ISSUE THREAD

**Issue by anant-k-singh** [Werter12/material-ui-audio-player#7]
Clicking player time should toggle between remaining play time and current play time.
![image](https://user-images.githubusercontent.com/22440924/80863691-a38d7e00-8c9b-11ea-9abd-d7b7d15fbbef.png)

**Comment by Werter12** [comment]
Hi, @anant-k-singh !
Nice suggestion! Do you think we should also hide whole progress time with this improvement? Because it would be kind of duplication of functionality.

**Comment by anant-k-singh** [comment]
Yes. 
Suppose length of audio track is 1 min (01:00), then clicking the 00:26 should be converted to -00:34.

**Comment by Werter12** [comment]
@anant-k-singh Hi! Sorry, for the late response. I really find your idea useful. That's why I implemented it. Please, check the latest release. Now, this toggle behavior is enabled. Also, you can use the `time` prop with `single` value, which will help you to get rid of the second timer. Besides, I've added `timePosition` which helps to pick a position for `single` timer.
